<?php
/**
 * Crius
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt
 *
 * @category   Crius
 * @package    Crius_GroupedProductsPro
 * @copyright  Copyright (c) 2011 Crius (http://www.criuscommerce.com)
 * @license    http://www.criuscommerce.com/CRIUS-LICENSE.txt
 */
?>
<?php
/**
 * Grouped product associated products table
 *
 * @see Crius_GroupedProductsPro_Block_View
 * @see Mage_Catalog_Block_Product_View_Type_Grouped
 */
?>
<?php $this->setPreconfiguredValue(); ?>
<?php $_product = $this->getProduct(); ?>
<?php $_associatedProducts = $this->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php $_countTierPriceColumns = ($this->showSeparateTierPrices()) ? count($this->getTierPricesGroupedByQuantity()) : 0 ?>
<?php echo $this->getChildHtml('product_type_data_extra') ?>
<table class="data-table grouped-items-table" id="super-product-table">
    <?php echo str_repeat('<col />', count($this->getTableAttributes()) + $_countTierPriceColumns) ?>
    <?php if ($_product->isSaleable()): ?>
    <?php if ($this->showQuantityFields()): ?>
    <col width="1" />
    <?php endif ?>
    <?php if ($this->showAddToCartForRows()): ?>
    <col width="1" />
    <?php endif ?>
    <?php endif ?>
    <!-- 
     <thead>
        <tr>
            <?php // Print attribute titles ?>
            <?php foreach ($this->getTableAttributes() as $attribute): ?>
                <?php $class = ($attribute->getFrontendInput() == 'price') ? ' class="a-right formattedprice sortcol-right"' : '' ?>
                <th<?php echo $class ?>><strong><?php echo $attribute->getStoreLabel() ?></strong></th>
                <?php // After price column, print tier price column titles ?>
                <?php if ($attribute->getFrontendInput() == 'price' && $this->showSeparateTierPrices()): ?>
                <?php foreach ($this->getTierPricesGroupedByQuantity() as $qty => $productTierPrices): ?>
                    <th class="a-right formattedprice sortcol-right"><strong><?php echo $qty ?>+</strong></th>
                <?php endforeach ?>
                <?php endif ?>
            <?php endforeach ?>
            <?php // Print quantity title ?>
            <?php if ($_product->isSaleable()): ?>
            <?php if ($this->showQuantityFields()): ?>
            <th class="a-center nosort"><strong><?php echo $this->__('Qty') ?></strong></th>
            <?php endif ?>
            <?php // Print add to cart title ?>
            <?php if ($this->showAddToCartForRows()): ?>
            <th class="nosort"><strong><?php echo $this->__('Add to Cart') ?></strong></th>
            <?php endif ?>
            <?php endif; ?>
        </tr>
    </thead> -->
   

    <tbody>
    <?php if ($_hasAssociatedProducts): ?>
    <?php // Print product rows ?>
    <?php foreach ($_associatedProducts as $_item): ?>
                <tr><td colspan="6" style="border-right:none !important;"><hr style="margin-bottom: 10px;"></td></tr>
        <tr>
            <?php // Print attributes ?>
           <td class="group-image">
            <?php foreach ($this->getTableAttributes() as $attribute): ?>
                <?php $_type = $attribute->getFrontendInput(); ?>
                
                
                    <?php if ($_type == 'media_image'): ?>
                        <?php // Render image ?>
                        <img src="<?php echo $this->helper('catalog/image')->init($_item, $attribute->getAttributeCode())->resize($this->getImageWidth(), $this->getImageHeight()); ?>" width="<?php echo $this->getImageWidth() ?>" height="<?php echo $this->getImageHeight() ?>" alt="<?php echo $_item->getName() ?>" />
                    	<!-- not used -->
                       
                    <?php else: ?>
                        
                    <?php endif; ?>
                
            <?php endforeach ?>
            </td>            
            	<?php // Render other attribute types ?>
                <?php if ($_item->getData($attribute->getAttributeCode())): ?>

                    <td class="group-title">
                    	<h4><?php echo $_item->getName(); ?></h4>
                    	<a class="detailslink" href="<?php echo $_item->getProductUrl(); ?>">View Details</a>
                    </td>
                   <td class="group-specs">
                    	<h4>Specifications</h4>
                    	
                    	<p>Size: <?php echo $_item->getAttributeText('c2c_size'); ?></p>
                    	<p>Color: <?php echo $_item->getAttributeText('c2c_color'); ?></p>
                    	<p>Type: <?php echo $_item->getAttributeText('c2c_type'); ?></p>
                    </td>
                <?php endif ?>
                
                <td class="group-price">
                <?php foreach ($this->getTableAttributes() as $attribute): ?>
            		<?php $_type = $attribute->getFrontendInput(); ?>
		               
		                	<?php if ($_type == 'price'): ?>
		                        <?php // Render price ?>
		                    	<h4>Price</h4>
		                    	<?php if ($this->getCanShowProductPrice($_item)): ?>
		                    		<?php echo $this->getPriceHtml($_item, true) ?>
		                        <?php if (!$this->showSeparateTierPrices()): ?>
		                            <?php echo $this->getTierPriceHtml($_item) ?>
		                        <?php endif ?>
		                    <?php endif; ?>
		                        
		                    <?php endif; ?>
		                
            <?php endforeach ?>
             </td>           
            <?php if ($_product->isSaleable()): ?>
            <?php if ($_item->isSaleable()) : ?>
                <?php // Print quantity field if enabled, otherwise make a hidden field ?>
                <?php if ($this->showQuantityFields()): ?>
                <td class="a-center group-qty">
                	 <h4>Quantity</h4>
                    <input type="text" name="super_group[<?php echo $_item->getId() ?>]" maxlength="12" value="<?php echo $_item->getQty()*1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
                </td>
                <?php else: ?>
                    <input type="hidden" name="super_group[<?php echo $_item->getId() ?>]" class="qty" value="1" />
                <?php endif; ?>
                <?php // Add to cart button for the row ?>
                <?php if ($this->showAddToCartForRows()): ?>
                <td class="group-btn">
                    <button class="button btn-cart" type="button" onclick="addGroupedRowToCart(this)" title="<?php echo $this->__('Add to Cart') ?>"><span><span>
                     <img src="/skin/frontend/response/default/images/AddCartButton.gif" /></span></span></button>

                </td>
                <?php endif ?>
            <?php else: ?>
                <?php // If not saleable, show out of stock instead of quantity and add-to-cart ?>
                <?php if ($this->showQuantityFields() && $this->showAddToCartForRows()): ?>
                <td colspan="2">
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                </td>
                <?php elseif ($this->showQuantityFields() || $this->showAddToCartForRows()): ?>
                <td>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                </td>
                <?php endif ?>
            <?php endif; ?>
            <?php endif; ?>
        </tr>

    <?php endforeach; ?>
    <?php else: ?>
       <tr>
           <td colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>"><?php echo $this->__('No options of this product are available.') ?></td>
       </tr>
    <?php endif; ?>
    </tbody>
</table>
<script type="text/javascript">
// Row styling
TableKit.options.rowEvenClass = 'even';
TableKit.options.rowOddClass = 'odd';
// Sorting rule for price column
TableKit.Sortable.addSortType(
	new TableKit.Sortable.Type('formattedprice', {
		pattern : /^[-+]?[\d]*\.?[\d]+(?:[eE][-+]?[\d]+)?/,
		normal : function(v) {
		    // Remove whitespace, commas and periods and grab the first thing that looks like a number
		    if (!v) {
		        v = "0";
		    }
			v = parseFloat(v.replace(/^\s*/, "").replace(/\s*$/, "").replace('.','').replace(',','').replace(/^.*?([-+]?[\d]*\.?[\d]+(?:[eE][-+]?[\d]+)?).*$/,"$1"));
			return isNaN(v) ? 0 : v;
		}
	})
);
function addGroupedRowToCart(button) {
    // Quantity for row
    var rowqty = Element.up(button, 'tr').down('input.qty').value;
    if (rowqty=='0') {
        rowqty = '1';
    }
    // Reset all quantities to zero
    Element.up(button, 'tbody').select('input.qty').each(function(qty) { qty.value = '0'; });
    // Re-insert current row's quantity
    Element.up(button, 'tr').down('input.qty').value = rowqty;
    // Submit form
    productAddToCartForm.submit(button);
}
</script>
