<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('our_brands')->toHtml() ?>

    <script type="text/javascript" src="<?php echo $this->getSkinUrl('assets/plg_caroufredsel/jquery.carouFredSel-6.2.1-packed.js') ?>"></script>

    <script type="text/javascript" src="<?php echo $this->getSkinUrl('assets/plg_caroufredsel/jquery.mousewheel.min.js') ?>"></script>

    <script type="text/javascript" src="<?php echo $this->getSkinUrl('assets/plg_caroufredsel/jquery.touchSwipe.min.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('assets/plg_caroufredsel/jquery.transit.min.js') ?>"></script>

<script type="text/javascript">
//<![CDATA[
    jQuery(document).ready(function(){
        jQuery('.slider-brands ul').carouFredSel({
            responsive: true,
            width: '100%',
            scroll: {
                items:1,
                duration:500
            },

            items: {
            //  height: '30%',  //  optionally resize item-height
                width  : '200',
                visible: {
                    min: 1,
                    max: 8
                }
            },
            /*mousewheel: true,
            swipe: {
                onMouse: true,
                onTouch: true
            },*/
            prev: '.slider-brands .prev',
            next: '.slider-brands .next',
            auto: false
        });
    });
//]]>
</script>